title: Dive into the deep, dark underweb
author: Hannah
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This website will expose the underbelly of the Internet.

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
